---
# Prerequisites
- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Ensure ethtool is installed
  apt:
    name: ethtool
    state: present

- name: Ensure mesh-announce target directory exists
  file:
    path: /opt/mesh-announce
    state: directory

# Git clone
- name: Ensure mesh-announce is installed
  git:
    repo: https://github.com/ffnord/mesh-announce.git
    dest: /opt/mesh-announce
  notify:
    - restart respondd

- name: Ensure respondd configuration is deployed
  template:
    src: etc/respondd.conf.j2
    dest: /etc/respondd.conf
  notify:
    - restart respondd

# Service setup
- name: Ensure mesh-announce service file is installed
  template:
    src: etc/systemd/system/respondd.service.j2
    dest: /etc/systemd/system/respondd.service
  notify:
    - restart respondd
  register:
    respondd_unit

- name: Ensure systemd services are reloaded if unit file changed
  systemd:
    daemon_reload: yes
  when: respondd_unit.changed

- name: Ensure mesh-announce service is enabled
  service:
    name: respondd
    enabled: yes
